//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.EmployeeTraining {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.EmployeeTraining.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience.
        /// </summary>
        public static string Audience {
            get {
                return ResourceManager.GetString("Audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string AudiencePrivate {
            get {
                return ResourceManager.GetString("AudiencePrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string AudiencePublic {
            get {
                return ResourceManager.GetString("AudiencePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been auto-registered to the following new event.
        /// </summary>
        public static string AutoRegisteredCardSubTitle {
            get {
                return ResourceManager.GetString("AutoRegisteredCardSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-registered!.
        /// </summary>
        public static string AutoRegisteredHeader {
            get {
                return ResourceManager.GetString("AutoRegisteredHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We regret to inform you that your following registered event has been cancelled.
        /// </summary>
        public static string CancellationCardSubTitle {
            get {
                return ResourceManager.GetString("CancellationCardSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled!.
        /// </summary>
        public static string CancellationHeader {
            get {
                return ResourceManager.GetString("CancellationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close registrations.
        /// </summary>
        public static string CloseRegistrationCardButton {
            get {
                return ResourceManager.GetString("CloseRegistrationCardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string CreatedByLabel {
            get {
                return ResourceManager.GetString("CreatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; time.
        /// </summary>
        public static string DateAndTimeLabel {
            get {
                return ResourceManager.GetString("DateAndTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionLabelCard {
            get {
                return ResourceManager.GetString("DescriptionLabelCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit event.
        /// </summary>
        public static string EditEventCardButton {
            get {
                return ResourceManager.GetString("EditEventCardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Description.
        /// </summary>
        public static string EventDescription {
            get {
                return ResourceManager.GetString("EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export registration details.
        /// </summary>
        public static string ExportDetailsCardButton {
            get {
                return ResourceManager.GetString("ExportDetailsCardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading image.
        /// </summary>
        public static string LoadingImageAltText {
            get {
                return ResourceManager.GetString("LoadingImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Registrations.
        /// </summary>
        public static string NumberOfRegistrations {
            get {
                return ResourceManager.GetString("NumberOfRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Users.
        /// </summary>
        public static string RegisteredUsers {
            get {
                return ResourceManager.GetString("RegisteredUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are {0}/{1} events:.
        /// </summary>
        public static string ReminderCardDescriptionText {
            get {
                return ResourceManager.GetString("ReminderCardDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View registered events.
        /// </summary>
        public static string ReminderCardRegisteredEventButton {
            get {
                return ResourceManager.GetString("ReminderCardRegisteredEventButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder!.
        /// </summary>
        public static string ReminderCardTitle {
            get {
                return ResourceManager.GetString("ReminderCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams Meeting.
        /// </summary>
        public static string TeamsMeetingText {
            get {
                return ResourceManager.GetString("TeamsMeetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Type.
        /// </summary>
        public static string TrainingType {
            get {
                return ResourceManager.GetString("TrainingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-Person.
        /// </summary>
        public static string TrainingTypeInPerson {
            get {
                return ResourceManager.GetString("TrainingTypeInPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Event.
        /// </summary>
        public static string TrainingTypeLiveEvent {
            get {
                return ResourceManager.GetString("TrainingTypeLiveEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue.
        /// </summary>
        public static string Venue {
            get {
                return ResourceManager.GetString("Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all events.
        /// </summary>
        public static string ViewAllEventsCardButton {
            get {
                return ResourceManager.GetString("ViewAllEventsCardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on &apos;{0}&apos; to start exploring new events..
        /// </summary>
        public static string WelcomeCardTeamContentFooter {
            get {
                return ResourceManager.GetString("WelcomeCardTeamContentFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string WelcomeCardTeamDiscoverButtonText {
            get {
                return ResourceManager.GetString("WelcomeCardTeamDiscoverButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the activities which I can help you with:.
        /// </summary>
        public static string WelcomeCardTeamHeading {
            get {
                return ResourceManager.GetString("WelcomeCardTeamHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking forward to discover and participate in new events? I am here to help you discover new events, participate in them &amp; keep track of their occurance. So, lets get started!.
        /// </summary>
        public static string WelcomeCardTeamIntro {
            get {
                return ResourceManager.GetString("WelcomeCardTeamIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Discover &amp; explore all events..
        /// </summary>
        public static string WelcomeCardTeamPoint1 {
            get {
                return ResourceManager.GetString("WelcomeCardTeamPoint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Register to the events you like..
        /// </summary>
        public static string WelcomeCardTeamPoint2 {
            get {
                return ResourceManager.GetString("WelcomeCardTeamPoint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Keep a track of all your completed events..
        /// </summary>
        public static string WelcomeCardTeamPoint3 {
            get {
                return ResourceManager.GetString("WelcomeCardTeamPoint3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Get notified about all your activities &amp; receive reminders of your upcoming registered events..
        /// </summary>
        public static string WelcomeCardTeamPoint4 {
            get {
                return ResourceManager.GetString("WelcomeCardTeamPoint4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
    }
}
